# @format
---
#============== CREATE USER
#check vars
- name: Set MySQL user host as private DNS
  set_fact:
    mysql_user_host_new_get: "{{ ansible_fqdn }}"
  when: "'laravel_dashboard_new' in group_names"

- name: Set MySQL user host as private DNS
  set_fact:
    mysql_user_host_new_get: "{{ ansible_fqdn }}"
  when: "'laravel_websocket_new' in group_names"

- name: Set MySQL user host as private DNS
  set_fact:
    mysql_user_host_new_seam: "{{ ansible_fqdn }}"
  when: "'laravel_seamless_new' in group_names"
