# @format
---
- name: Generate combined list of allowed IPs including public_nginx_proxy
  set_fact:
    laravel_dashboard_allowed_ips_final: >-
      {{
        laravel_allowed_subnets_dashboard +
       (
          [
            groups['bastion_host_phpmyadmin'],
            groups['laravel_dashboard_new'],
            groups['laravel_websocket_new'],
            groups['laravel_calculator_new'],
            groups['laravel_seamless_new'],
            groups['nextjs_frontend'],
            groups['jenkins_prometheus'],
            groups['public_nginx_proxy']
          ]
          | flatten
          | map('extract', hostvars, 'ansible_default_ipv4')
          | map(attribute='address')
          | list
        )
      }}

- name: lrv dashboar - Ensure Nginx installed
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: lrv dashboar - Ensure Nginx service is running
  service:
    name: nginx
    state: started
    enabled: true
- name: lrv dashboar - Set custom fact for IP & DNS
  set_fact:
    private_ip_dashboard: "{{ ansible_default_ipv4.address }}"

- name: lrv dashboar - Deploy Nginx config for Laravel private ip
  template:
    src: laravel.conf.j2
    dest: /etc/nginx/sites-available/{{ name_file_conf_dashboard }}.conf
    owner: root
    group: root
    mode: 0644

- name: lrv dashboar - Enable Laravel Nginx site
  file:
    src: /etc/nginx/sites-available/{{ name_file_conf_dashboard }}.conf
    dest: /etc/nginx/sites-enabled/{{ name_file_conf_dashboard }}.conf
    state: link
    force: yes

- name: lrv dashboar - Disable default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: lrv dashboar - Test Nginx configuration
  command: nginx -t
  register: nginx_test_result
  failed_when: nginx_test_result.rc != 0

- name: lrv dashboar - Reload Nginx
  service:
    name: nginx
    state: reloaded
