# @format
---
- name: lrv dashboard - Set permissions for Laravel directories
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0775"
    recurse: yes
  loop:
    - "{{ laravel_app_path_dashboard }}"
    - "{{ laravel_app_path_dashboard }}/storage"
    - "{{ laravel_app_path_dashboard }}/bootstrap/cache"
