# @format

- hosts: node_exporter
  become: yes
  tasks:
    - name: Install Node Exporter
      shell: |
        useradd -rs /bin/false node_exporter
        wget https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
        tar -xvzf node_exporter-*.tar.gz
        cp node_exporter-*/node_exporter /usr/local/bin/
        cat <<EOF > /etc/systemd/system/node_exporter.service
        [Unit]
        Description=Node Exporter
        After=network.target

        [Service]
        User=node_exporter
        ExecStart=/usr/local/bin/node_exporter

        [Install]
        WantedBy=default.target
        EOF
        systemctl daemon-reexec
        systemctl enable node_exporter
        systemctl start node_exporter
