# @format
---
- name: seamless Configure Nginx as reverse proxy to laravel in private subnet
  template:
    src: seam_nginx_laravel_proxy.conf.j2
    dest: /etc/nginx/sites-available/{{ target_dest_nginx_seamless }}
    owner: root
    group: root
    mode: 0644

- name: seamless Ensure Nginx service is running
  service:
    name: nginx
    state: started
    enabled: true

- name: seamless Ensure SSL directory exists
  file:
    path: /etc/ssl/laravel
    state: directory
    mode: "0755"

- name: seamless Upload SSL certificate
  copy:
    src: ssl/{{ target_file_ssl_seamless }}.pem
    dest: /etc/ssl/laravel/{{ target_file_ssl_seamless }}.pem
    owner: root
    group: root
    mode: "0644"

- name: seamless Upload SSL key
  copy:
    src: ssl/{{ target_file_ssl_seamless }}.key
    dest: /etc/ssl/laravel/{{ target_file_ssl_seamless }}.key
    owner: root
    group: root
    mode: "0600"

- name: seamless Enable Nginx config
  file:
    src: /etc/nginx/sites-available/{{ target_dest_nginx_seamless }}
    dest: /etc/nginx/sites-enabled/{{ target_dest_nginx_seamless }}
    state: link
    force: yes

- name: seamless Remove default site if present in sites-enabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: seamless Test Nginx configuration
  command: nginx -t
  register: nginx_test_result
  failed_when: nginx_test_result.rc != 0

- name: seamless Reload Nginx
  service:
    name: nginx
    state: reloaded
