# @format
---
# roles/playbook/laravel/tasks/migrate.yaml
- name: Add safe Git directory
  shell: git config --global --add safe.directory "{{ laravel_app_path_calc }}"
  become: false

- name: Pull latest code from git
  git:
    repo: "{{ laravel_repo_url_calc }}"
    dest: "{{ laravel_app_path_calc }}"
    version: "{{ laravel_repo_branch_calc }}"
    force: yes
    accept_hostkey: yes

- name: Run Laravel migrate (allow failure)
  shell: |
    php artisan migrate --no-interaction --ansi || true
  args:
    chdir: "{{ laravel_app_path_calc }}"
    executable: /bin/bash
