# @format
---
- name: lrvl ws - Set permissions for Laravel directories
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0775"
    recurse: yes
  loop:
    - "{{ laravel_app_path_ws }}"
    - "{{ laravel_app_path_ws }}/storage"
    - "{{ laravel_app_path_ws }}/bootstrap/cache"
