# @format
---
- name: lrv seam - Ensure git is installed
  apt:
    name: git
    state: present
    update_cache: yes

- name: lrv seam - Ensure {{ laravel_app_path_seam }} is marked as safe.directory for git
  command: git config --global --add safe.directory {{ laravel_app_path_seam }}
  become: yes
  become_user: root
  args:
    creates: /root/.gitconfig

- name: lrv seam - Clone Laravel repo
  git:
    repo: "{{ laravel_repo_url_seam }}"
    dest: "{{ laravel_app_path_seam }}"
    update: yes
    force: yes
    version: "{{ laravel_repo_branch_seam }}"
