# @format
---
- name: laravel seam - Install Composer dependencies (DEV)
  command: composer update --no-interaction --prefer-dist --optimize-autoloader
  args:
    chdir: "{{ laravel_app_path_seam }}"
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"
  when: env == 'dev'

- name: laravel seam - Install Composer dependencies (PROD)
  command: composer install --no-interaction --prefer-dist --optimize-autoloader
  args:
    chdir: "{{ laravel_app_path_seam }}"
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"
  when: env == 'prod'

- name: laravel seam - Generate Laravel app key (dengan timeout)
  command: php artisan key:generate
  args:
    chdir: "{{ laravel_app_path_seam }}"
  async: 30
  poll: 5
  environment:
    APP_ENV: production
  when: env == 'prod'

- name: laravel seam - Generate Laravel app key (dengan timeout)
  command: php artisan key:generate
  args:
    chdir: "{{ laravel_app_path_seam }}"
  async: 30
  poll: 5
  environment:
    APP_ENV: local
  when: env != 'prod'

- name: laravel seam - Create storage symbolic link
  command: php artisan storage:link
  args:
    chdir: "{{ laravel_app_path_seam }}"
  environment:
    APP_ENV: production
  when: env == 'prod'

- name: laravel seam - Create storage symbolic link
  command: php artisan storage:link
  args:
    chdir: "{{ laravel_app_path_seam }}"
  environment:
    APP_ENV: local
  when: env != 'prod'

- name: laravel seam - Run Laravel migrate and seed
  command: php artisan migrate --force
  args:
    chdir: "{{ laravel_app_path_seam }}"
  environment:
    APP_ENV: production
  when: env == 'prod'

- name: laravel seam - Run Laravel migrate and seed
  command: php artisan migrate --force
  args:
    chdir: "{{ laravel_app_path_seam }}"
  environment:
    APP_ENV: local
  when: env != 'prod'
